
package proyectotextos;


public class JFArchivos extends javax.swing.JFrame {

    //Se crea la funcion de centrar el menu al centro de la pantalla
    public JFArchivos() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCrear = new javax.swing.JMenu();
        jLeer = new javax.swing.JMenu();
        jEliminar = new javax.swing.JMenu();
        jRenombrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("EVIDENCIA DE APRENDIZAJE");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("U1 - EA - Hector Rodriguez - Matricula: ES1821017072");

        jCrear.setText("Crear");
        jCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCrearMouseClicked(evt);
            }
        });
        jMenuBar1.add(jCrear);

        jLeer.setText("Leer");
        jLeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLeerMouseClicked(evt);
            }
        });
        jMenuBar1.add(jLeer);

        jEliminar.setText("Eliminar");
        jEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEliminarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jEliminar);

        jRenombrar.setText("Renombrar");
        jRenombrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRenombrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRenombrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Se crea la funcion del boton crear donde mostrara el menu para creacion de textos
    private void jCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCrearMouseClicked
        crearA c = new crearA();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCrearMouseClicked
// Se crea la funcion del boton leer donde mostrara el menu para leer textos
    private void jLeerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLeerMouseClicked
        leerA l = new leerA();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLeerMouseClicked
// Se crea la funcion del boton eliminar donde mostrara el menu para eliminar textos
    private void jEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEliminarMouseClicked
        eliminarA e = new eliminarA();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jEliminarMouseClicked
// Se crea la funcion del boton renombrar donde mostrara el menu para renombre de textos
    private void jRenombrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRenombrarMouseClicked
        renombrarA r = new renombrarA();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jRenombrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCrear;
    private javax.swing.JMenu jEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jLeer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jRenombrar;
    // End of variables declaration//GEN-END:variables
}
